language: java
jdk:
    - oraclejdk8

cache:
  directories:
    - $HOME/.m2
stages:
    - Build
    - Release
env:
    global:
    - DEPLOY_REPO=Taskana/TaskanaSimpleHistory
jobs:
  include:
    - stage: Build
      script:
        - ci/build.sh lib/ $TRAVIS_TAG
    - stage: Release
      script:
        - ci/release.sh lib/taskana-simplehistory-provider lib/ $TRAVIS_TAG
          && ci/release.sh lib/taskana-simplehistory-rest-spring lib/ $TRAVIS_TAG
          && ci/change_version.sh -i -m "lib/" 
          && ci/commitPoms.sh
      if: repo = env(DEPLOY_REPO) AND (tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ OR branch = master) AND type != pull_request
