language: java
jdk:
  - oraclejdk8

stages:
  - Build
  - Release

env:
  global:
    - DEPLOY_REPO=Taskana/TaskanaSimpleHistory
  
jobs:
  include:
    - stage: Build
      script:
        - mvn clean install -q -f lib -Dmaven.javadoc.skip=true
    - stage: Release
      script:
        - ci/release.sh lib/taskana-simplehistory-provider $TRAVIS_TAG
          && ci/release.sh lib/taskana-simplehistory-rest-spring $TRAVIS_TAG
          && ci/change_version.sh -i -m "lib/" 
          && ci/commitPoms.sh
      if: repo = env(DEPLOY_REPO) AND (tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ OR branch = master) AND type != pull_request
